baseURL = "https://www.linkace.org/"
languageCode = "en-us"
title = "LinkAce"
assetDir = "./assets/dist"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
  DemoUrl = "https://demo.linkace.org"
  WikiDockerSetupUrl = "/docs/v1/setup/"
  DockerHubUrl = "https://hub.docker.com/r/linkace/linkace"
  WikiServerSetupUrl = "/docs/v1/setup/setup-without-docker/"
